// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: sample_manager.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SampleManagerClient is the client API for SampleManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SampleManagerClient interface {
	CreateSampleMapping(ctx context.Context, in *SampleMappingRequest, opts ...grpc.CallOption) (*SampleMappingResponse, error)
	UpdateSampleMapping(ctx context.Context, in *SampleMappingRequest, opts ...grpc.CallOption) (*SampleMappingResponse, error)
	GetSampleIDs(ctx context.Context, in *GetSampleIDsRequest, opts ...grpc.CallOption) (*GetSampleIDsResponse, error)
}

type sampleManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewSampleManagerClient(cc grpc.ClientConnInterface) SampleManagerClient {
	return &sampleManagerClient{cc}
}

func (c *sampleManagerClient) CreateSampleMapping(ctx context.Context, in *SampleMappingRequest, opts ...grpc.CallOption) (*SampleMappingResponse, error) {
	out := new(SampleMappingResponse)
	err := c.cc.Invoke(ctx, "/SampleManager/CreateSampleMapping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sampleManagerClient) UpdateSampleMapping(ctx context.Context, in *SampleMappingRequest, opts ...grpc.CallOption) (*SampleMappingResponse, error) {
	out := new(SampleMappingResponse)
	err := c.cc.Invoke(ctx, "/SampleManager/UpdateSampleMapping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sampleManagerClient) GetSampleIDs(ctx context.Context, in *GetSampleIDsRequest, opts ...grpc.CallOption) (*GetSampleIDsResponse, error) {
	out := new(GetSampleIDsResponse)
	err := c.cc.Invoke(ctx, "/SampleManager/GetSampleIDs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SampleManagerServer is the server API for SampleManager service.
// All implementations must embed UnimplementedSampleManagerServer
// for forward compatibility
type SampleManagerServer interface {
	CreateSampleMapping(context.Context, *SampleMappingRequest) (*SampleMappingResponse, error)
	UpdateSampleMapping(context.Context, *SampleMappingRequest) (*SampleMappingResponse, error)
	GetSampleIDs(context.Context, *GetSampleIDsRequest) (*GetSampleIDsResponse, error)
	mustEmbedUnimplementedSampleManagerServer()
}

// UnimplementedSampleManagerServer must be embedded to have forward compatible implementations.
type UnimplementedSampleManagerServer struct {
}

func (UnimplementedSampleManagerServer) CreateSampleMapping(context.Context, *SampleMappingRequest) (*SampleMappingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSampleMapping not implemented")
}
func (UnimplementedSampleManagerServer) UpdateSampleMapping(context.Context, *SampleMappingRequest) (*SampleMappingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSampleMapping not implemented")
}
func (UnimplementedSampleManagerServer) GetSampleIDs(context.Context, *GetSampleIDsRequest) (*GetSampleIDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSampleIDs not implemented")
}
func (UnimplementedSampleManagerServer) mustEmbedUnimplementedSampleManagerServer() {}

// UnsafeSampleManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SampleManagerServer will
// result in compilation errors.
type UnsafeSampleManagerServer interface {
	mustEmbedUnimplementedSampleManagerServer()
}

func RegisterSampleManagerServer(s grpc.ServiceRegistrar, srv SampleManagerServer) {
	s.RegisterService(&SampleManager_ServiceDesc, srv)
}

func _SampleManager_CreateSampleMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SampleMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SampleManagerServer).CreateSampleMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SampleManager/CreateSampleMapping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SampleManagerServer).CreateSampleMapping(ctx, req.(*SampleMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SampleManager_UpdateSampleMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SampleMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SampleManagerServer).UpdateSampleMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SampleManager/UpdateSampleMapping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SampleManagerServer).UpdateSampleMapping(ctx, req.(*SampleMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SampleManager_GetSampleIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSampleIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SampleManagerServer).GetSampleIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SampleManager/GetSampleIDs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SampleManagerServer).GetSampleIDs(ctx, req.(*GetSampleIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SampleManager_ServiceDesc is the grpc.ServiceDesc for SampleManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SampleManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SampleManager",
	HandlerType: (*SampleManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSampleMapping",
			Handler:    _SampleManager_CreateSampleMapping_Handler,
		},
		{
			MethodName: "UpdateSampleMapping",
			Handler:    _SampleManager_UpdateSampleMapping_Handler,
		},
		{
			MethodName: "GetSampleIDs",
			Handler:    _SampleManager_GetSampleIDs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sample_manager.proto",
}
