// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: sample_manager.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SampleMappingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SampleProductID string `protobuf:"bytes,1,opt,name=sampleProductID,proto3" json:"sampleProductID,omitempty"`
	ProductID       string `protobuf:"bytes,2,opt,name=productID,proto3" json:"productID,omitempty"`
	CustomerSegment string `protobuf:"bytes,3,opt,name=customerSegment,proto3" json:"customerSegment,omitempty"`
}

func (x *SampleMappingRequest) Reset() {
	*x = SampleMappingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sample_manager_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SampleMappingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleMappingRequest) ProtoMessage() {}

func (x *SampleMappingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sample_manager_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleMappingRequest.ProtoReflect.Descriptor instead.
func (*SampleMappingRequest) Descriptor() ([]byte, []int) {
	return file_sample_manager_proto_rawDescGZIP(), []int{0}
}

func (x *SampleMappingRequest) GetSampleProductID() string {
	if x != nil {
		return x.SampleProductID
	}
	return ""
}

func (x *SampleMappingRequest) GetProductID() string {
	if x != nil {
		return x.ProductID
	}
	return ""
}

func (x *SampleMappingRequest) GetCustomerSegment() string {
	if x != nil {
		return x.CustomerSegment
	}
	return ""
}

type SampleMappingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID              int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	SampleProductID string `protobuf:"bytes,2,opt,name=sampleProductID,proto3" json:"sampleProductID,omitempty"`
	ProductID       string `protobuf:"bytes,3,opt,name=productID,proto3" json:"productID,omitempty"`
	CustomerSegment string `protobuf:"bytes,4,opt,name=customerSegment,proto3" json:"customerSegment,omitempty"`
	Error           *Error `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *SampleMappingResponse) Reset() {
	*x = SampleMappingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sample_manager_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SampleMappingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleMappingResponse) ProtoMessage() {}

func (x *SampleMappingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sample_manager_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleMappingResponse.ProtoReflect.Descriptor instead.
func (*SampleMappingResponse) Descriptor() ([]byte, []int) {
	return file_sample_manager_proto_rawDescGZIP(), []int{1}
}

func (x *SampleMappingResponse) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *SampleMappingResponse) GetSampleProductID() string {
	if x != nil {
		return x.SampleProductID
	}
	return ""
}

func (x *SampleMappingResponse) GetProductID() string {
	if x != nil {
		return x.ProductID
	}
	return ""
}

func (x *SampleMappingResponse) GetCustomerSegment() string {
	if x != nil {
		return x.CustomerSegment
	}
	return ""
}

func (x *SampleMappingResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetSampleIDsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerSegments []string `protobuf:"bytes,1,rep,name=customerSegments,proto3" json:"customerSegments,omitempty"`
	ProductIDs       []string `protobuf:"bytes,2,rep,name=productIDs,proto3" json:"productIDs,omitempty"`
}

func (x *GetSampleIDsRequest) Reset() {
	*x = GetSampleIDsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sample_manager_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSampleIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSampleIDsRequest) ProtoMessage() {}

func (x *GetSampleIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sample_manager_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSampleIDsRequest.ProtoReflect.Descriptor instead.
func (*GetSampleIDsRequest) Descriptor() ([]byte, []int) {
	return file_sample_manager_proto_rawDescGZIP(), []int{2}
}

func (x *GetSampleIDsRequest) GetCustomerSegments() []string {
	if x != nil {
		return x.CustomerSegments
	}
	return nil
}

func (x *GetSampleIDsRequest) GetProductIDs() []string {
	if x != nil {
		return x.ProductIDs
	}
	return nil
}

type GetSampleIDsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SampleIDs []string `protobuf:"bytes,1,rep,name=sampleIDs,proto3" json:"sampleIDs,omitempty"`
	Error     *Error   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *GetSampleIDsResponse) Reset() {
	*x = GetSampleIDsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sample_manager_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSampleIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSampleIDsResponse) ProtoMessage() {}

func (x *GetSampleIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sample_manager_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSampleIDsResponse.ProtoReflect.Descriptor instead.
func (*GetSampleIDsResponse) Descriptor() ([]byte, []int) {
	return file_sample_manager_proto_rawDescGZIP(), []int{3}
}

func (x *GetSampleIDsResponse) GetSampleIDs() []string {
	if x != nil {
		return x.SampleIDs
	}
	return nil
}

func (x *GetSampleIDsResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sample_manager_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_sample_manager_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_sample_manager_proto_rawDescGZIP(), []int{4}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_sample_manager_proto protoreflect.FileDescriptor

var file_sample_manager_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x88, 0x01, 0x0a, 0x14, 0x53, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x28, 0x0a, 0x0f, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x22, 0xb7, 0x01, 0x0a, 0x15, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x61, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x28, 0x0a, 0x0f, 0x73,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x49, 0x44, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x53,
	0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x61, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2a, 0x0a, 0x10, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x53, 0x65,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x10, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1e,
	0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x73, 0x22, 0x52,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x49, 0x44, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x73, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x49, 0x44, 0x73, 0x12, 0x1c, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0x35, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xde, 0x01, 0x0a, 0x0d, 0x53, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x46, 0x0a, 0x13, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x61, 0x70, 0x70, 0x69,
	0x6e, 0x67, 0x12, 0x15, 0x2e, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x61, 0x70, 0x70, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x53, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x15, 0x2e, 0x53, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0c, 0x47,
	0x65, 0x74, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x49, 0x44, 0x73, 0x12, 0x14, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x15, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x49, 0x44, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sample_manager_proto_rawDescOnce sync.Once
	file_sample_manager_proto_rawDescData = file_sample_manager_proto_rawDesc
)

func file_sample_manager_proto_rawDescGZIP() []byte {
	file_sample_manager_proto_rawDescOnce.Do(func() {
		file_sample_manager_proto_rawDescData = protoimpl.X.CompressGZIP(file_sample_manager_proto_rawDescData)
	})
	return file_sample_manager_proto_rawDescData
}

var file_sample_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sample_manager_proto_goTypes = []interface{}{
	(*SampleMappingRequest)(nil),  // 0: SampleMappingRequest
	(*SampleMappingResponse)(nil), // 1: SampleMappingResponse
	(*GetSampleIDsRequest)(nil),   // 2: GetSampleIDsRequest
	(*GetSampleIDsResponse)(nil),  // 3: GetSampleIDsResponse
	(*Error)(nil),                 // 4: Error
}
var file_sample_manager_proto_depIdxs = []int32{
	4, // 0: SampleMappingResponse.error:type_name -> Error
	4, // 1: GetSampleIDsResponse.Error:type_name -> Error
	0, // 2: SampleManager.CreateSampleMapping:input_type -> SampleMappingRequest
	0, // 3: SampleManager.UpdateSampleMapping:input_type -> SampleMappingRequest
	2, // 4: SampleManager.GetSampleIDs:input_type -> GetSampleIDsRequest
	1, // 5: SampleManager.CreateSampleMapping:output_type -> SampleMappingResponse
	1, // 6: SampleManager.UpdateSampleMapping:output_type -> SampleMappingResponse
	3, // 7: SampleManager.GetSampleIDs:output_type -> GetSampleIDsResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sample_manager_proto_init() }
func file_sample_manager_proto_init() {
	if File_sample_manager_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sample_manager_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SampleMappingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sample_manager_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SampleMappingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sample_manager_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSampleIDsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sample_manager_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSampleIDsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sample_manager_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sample_manager_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sample_manager_proto_goTypes,
		DependencyIndexes: file_sample_manager_proto_depIdxs,
		MessageInfos:      file_sample_manager_proto_msgTypes,
	}.Build()
	File_sample_manager_proto = out.File
	file_sample_manager_proto_rawDesc = nil
	file_sample_manager_proto_goTypes = nil
	file_sample_manager_proto_depIdxs = nil
}
